services:
  react_app:
    build: ./backend
    container_name: ticketflow_react_app
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8001:8001"
    depends_on:
      - react_db
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    command: >
      sh -c "
      sleep 5 &&
      pnpm prisma generate &&
      pnpm prisma migrate deploy &&
      pnpm dev
      "
    networks:
      - ticket-network

  react_frontend:
    build: ./frontend
    container_name: ticketflow_react_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - react_app
    networks:
      - ticket-network

  react_db:
    image: mysql:8
    container_name: ticketflow_react_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketflow
      MYSQL_USER: adminTicketFlow
      MYSQL_PASSWORD: "flow!@#"

    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ticket-network

volumes:
  mysql_data:

networks:
  ticket-network:
    driver: bridge
